### ISSUE TITLE
Doesn't work with the latest Flutter release 3.29.0

### ISSUE THREAD

**Issue by jdevp** [pichillilorenzo/flutter_inappwebview#2532]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

It seems that this plugin doesn't work with the Flutter release 3.29.0 any more. 

```
.pub-cache/hosted/pub.dev/flutter_inappwebview-5.8.0/android/src/main/java/com/pichillilorenzo/flutter_inappwebview/InAppWebViewFlutterPlugin.java:43: error: cannot find symbol
  public PluginRegistry.Registrar registrar;
```

### Expected Behavior

The plugin should work with the latest Flutter release

### Steps with code example to reproduce

<details>
<summary>Steps with code example to reproduce</summary>

```dart
flutter run app
```
</details>

### Stacktrace/Logs

<details>
<summary>Stacktrace/Logs</summary>

```
.pub-cache/hosted/pub.dev/flutter_inappwebview-5.8.0/android/src/main/java/com/pichillilorenzo/flutter_inappwebview/InAppWebViewFlutterPlugin.java:43: error: cannot find symbol
  public PluginRegistry.Registrar registrar;
```
</details>

### Flutter version

v3.29.0

### Operating System, Device-specific and/or Tool

Android 34+

### Plugin version

v5.8.0

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by jdevp** [comment]
It seems to be fixed in the latest version. Closed the issue.
