### ISSUE TITLE
xcode26.4.1 Compilation error

### ISSUE THREAD

**Issue by zhangwenxia** [pichillilorenzo/flutter_inappwebview#2830]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

After upgrading macOS to Tahoe 26.4.1 and updating Xcode to version 26.4.1, there were compilation errors：
Swift Compiler Error (Xcode): Protocol 'ASWebAuthenticationPresentationContextProviding' requires 'presentationAnchor(for:)' to be available in iOS 11.0 and newer
/Users/zhang/.pub-cache/hosted/pub.flutter-io.cn/flutter_inappwebview_ios-1.1.2/ios/Classes/WebAuthenticationSession/WebAuthenticationSession.swift:91:16

### Expected Behavior

Compilate correctly

### Steps with code example to reproduce

Update to the last Xcode version 26.4
Run an application with inappwebview package
Receive compilation error.

### Stacktrace/Logs

no

### Flutter version

v3.24.4

### Operating System, Device-specific and/or Tool

Xcode 26.4.1
macOS 26.4.1

### Plugin version

6.1.5

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by tadelv** [comment]
There's already an open fix for this: **#2809** (covers both the iOS and macOS sub-plugins). Confirmed it resolves the Xcode 26.4 / Swift 6.3 build here — pinning `flutter_inappwebview_ios` + `flutter_inappwebview_macos` to that branch via a `dependency_override`, `flutter build macos` completes cleanly.

Root cause for anyone landing here: `WebAuthenticationSession` declares the `ASWebAuthenticationPresentationContextProviding` conformance unconditionally, but annotates the `presentationAnchor(for:)` witness with a *narrower* `@available(...)` than the protocol requirement. Swift 6.3 (bundled with Xcode 26.4) promotes that "witness less available than requirement" mismatch from a warning to a **hard error** — Xcode 26.3 still builds.

Workaround until #2809 merges and a release ships: build with **Xcode 26.3**, or `dependency_override` the two platform packages to the #2809 branch.
