### ISSUE TITLE
alert dialog crash from 5.4.4

### ISSUE THREAD

**Issue by saixin** [pichillilorenzo/flutter_inappwebview#1456]
with version 5.4.3+8 everything works fine. After upgrade to 5.4.4, it can load the h5 web fine, but if the web contain alert dialog ,the app will crash(only android device).

[√] Flutter (Channel stable, 3.3.0, on Microsoft Windows [版本 10.0.19045.2311], locale zh-CN)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Enterprise 2022 17.4.2)  
[√] Android Studio (version 2021.1)
[√] VS Code (version 1.70.0)

crash log

> E/AndroidRuntime( 6547): java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/fragment/app/FragmentActivity;
E/AndroidRuntime( 6547): 	at com.pichillilorenzo.flutter_inappwebview.InAppWebViewFlutterPlugin.onAttachedToEngine(InAppWebViewFlutterPlugin.java:82)
E/AndroidRuntime( 6547): 	at com.pichillilorenzo.flutter_inappwebview.InAppWebViewFlutterPlugin.onAttachedToEngine(InAppWebViewFlutterPlugin.java:71)
E/AndroidRuntime( 6547): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.add(FlutterEngineConnectionRegistry.java:144)
E/AndroidRuntime( 6547): 	at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:24)
E/AndroidRuntime( 6547): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 6547): 	at io.flutter.embedding.engine.plugins.util.GeneratedPluginRegister.registerGeneratedPlugins(GeneratedPluginRegister.java:80)
E/AndroidRuntime( 6547): 	at io.flutter.embedding.android.FlutterActivity.configureFlutterEngine(FlutterActivity.java:1086)
E/AndroidRuntime( 6547): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:205)
E/AndroidRuntime( 6547): 	at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:498)
E/AndroidRuntime( 6547): 	at android.app.Activity.performCreate(Activity.java:8305)
E/AndroidRuntime( 6547): 	at android.app.Activity.performCreate(Activity.java:8284)
E/AndroidRuntime( 6547): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1417)
E/AndroidRuntime( 6547): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3626)
E/AndroidRuntime( 6547): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3782)
E/AndroidRuntime( 6547): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
E/AndroidRuntime( 6547): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime( 6547): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime( 6547): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
E/AndroidRuntime( 6547): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime( 6547): 	at android.os.Looper.loopOnce(Looper.java:201)
E/AndroidRuntime( 6547): 	at android.os.Looper.loop(Looper.java:288)
E/AndroidRuntime( 6547): 	at android.app.ActivityThread.main(ActivityThread.java:7872)
E/AndroidRuntime( 6547): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 6547): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/AndroidRuntime( 6547): Caused by: java.lang.ClassNotFoundException: androidx.fragment.app.FragmentActivity
E/AndroidRuntime( 6547): 	at java.lang.VMClassLoader.findLoadedClass(Native Method)
E/AndroidRuntime( 6547): 	at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
E/AndroidRuntime( 6547): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
E/AndroidRuntime( 6547): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/AndroidRuntime( 6547): 	... 25 more
E/AndroidRuntime( 6547): Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/activity/ComponentActivity;
E/AndroidRuntime( 6547): 	... 25 more
E/AndroidRuntime( 6547): Caused by: java.lang.ClassNotFoundException: androidx.activity.ComponentActivity
E/AndroidRuntime( 6547): 	at java.lang.VMClassLoader.findLoadedClass(Native Method)
E/AndroidRuntime( 6547): 	at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
E/AndroidRuntime( 6547): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
E/AndroidRuntime( 6547): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/AndroidRuntime( 6547): 	... 25 more
E/AndroidRuntime( 6547): Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/core/content/OnConfigurationChangedProvider;
E/AndroidRuntime( 6547): 	... 25 more
E/AndroidRuntime( 6547): Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.core.content.OnConfigurationChangedProvider" on path: DexPathList[[zip file "/data/app/~~IjjD86VBqgT7N9TJs-0wSg==/com.saixin.www-tKHKmvbYyHvajcvvBCSNtA==/base.apk"],nativeLibraryDirectories=[/data/app/~~IjjD86VBqgT7N9TJs-0wSg==/com.saixin.www-tKHKmvbYyHvajcvvBCSNtA==/lib/x86_64, /data/app/~~IjjD86VBqgT7N9TJs-0wSg==/com.saixin.www-tKHKmvbYyHvajcvvBCSNtA==/base.apk!/lib/x86_64, /system/lib64, /system_ext/lib64]]
E/AndroidRuntime( 6547): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
E/AndroidRuntime( 6547): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
E/AndroidRuntime( 6547): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/AndroidRuntime( 6547): 	... 25 more
I/Process ( 6547): Sending signal. PID: 6547 SIG: 9
Lost connection to device.
Exited (sigterm)

**Comment by pichillilorenzo** [comment]
Cold you post logs?

**Comment by saixin** [comment]
`E/AndroidRuntime(23867): java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/fragment/app/FragmentActivity;
E/AndroidRuntime(23867): 	at com.pichillilorenzo.flutter_inappwebview.InAppWebViewFlutterPlugin.onAttachedToEngine(InAppWebViewFlutterPlugin.java:82)
E/AndroidRuntime(23867): 	at com.pichillilorenzo.flutter_inappwebview.InAppWebViewFlutterPlugin.onAttachedToEngine(InAppWebViewFlutterPlugin.java:71)
E/AndroidRuntime(23867): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.add(FlutterEngineConnectionRegistry.java:144)
E/AndroidRuntime(23867): 	at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:24)
E/AndroidRuntime(23867): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(23867): 	at io.flutter.embedding.engine.plugins.util.GeneratedPluginRegister.registerGeneratedPlugins(GeneratedPluginRegister.java:80)
E/AndroidRuntime(23867): 	at io.flutter.embedding.android.FlutterActivity.configureFlutterEngine(FlutterActivity.java:1086)
E/AndroidRuntime(23867): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:205)
E/AndroidRuntime(23867): 	at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:498)
E/AndroidRuntime(23867): 	at android.app.Activity.performCreate(Activity.java:7136)
E/AndroidRuntime(23867): 	at android.app.Activity.performCreate(Activity.java:7127)
E/AndroidRuntime(23867): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
E/AndroidRuntime(23867): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
E/AndroidRuntime(23867): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
E/AndroidRuntime(23867): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
E/AndroidRuntime(23867): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
E/AndroidRuntime(23867): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
E/AndroidRuntime(23867): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
E/AndroidRuntime(23867): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(23867): 	at android.os.Looper.loop(Looper.java:193)
E/AndroidRuntime(23867): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
E/AndroidRuntime(23867): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(23867): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/AndroidRuntime(23867): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
E/AndroidRuntime(23867): Caused by: java.lang.ClassNotFoundException: androidx.fragment.app.FragmentActivity
E/AndroidRuntime(23867): 	at java.lang.VMClassLoader.findLoadedClass(Native Method)
E/AndroidRuntime(23867): 	at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
E/AndroidRuntime(23867): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
E/AndroidRuntime(23867): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/AndroidRuntime(23867): 	... 24 more
E/AndroidRuntime(23867): Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/activity/ComponentActivity;
E/AndroidRuntime(23867): 	... 24 more
E/AndroidRuntime(23867): Caused by: java.lang.ClassNotFoundException: androidx.activity.ComponentActivity
E/AndroidRuntime(23867): 	at java.lang.VMClassLoader.findLoadedClass(Native Method)
E/AndroidRuntime(23867): 	at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
E/AndroidRuntime(23867): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
E/AndroidRuntime(23867): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/AndroidRuntime(23867): 	... 24 more
E/AndroidRuntime(23867): Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/core/content/OnConfigurationChangedProvider;
E/AndroidRuntime(23867): 	... 24 more
E/AndroidRuntime(23867): Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.core.content.OnConfigurationChangedProvider" on path: DexPathList[[zip file "/data/app/com.saixin.www-ZARlT54jcdbkocO3agshwQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.saixin.www-ZARlT54jcdbkocO3agshwQ==/lib/x86, /data/app/com.saixin.www-ZARlT54jcdbkocO3agshwQ==/base.apk!/lib/x86, /system/lib]]
E/AndroidRuntime(23867): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
E/AndroidRuntime(23867): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
E/AndroidRuntime(23867): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/AndroidRuntime(23867): 	... 24 more
I/Process (23867): Sending signal. PID: 23867 SIG: 9
Lost connection to device.
Exited (sigterm)`
