### ISSUE TITLE
flutter_inappwebview  it not running in android 33

### ISSUE THREAD

**Issue by Sayedmdkaif** [pichillilorenzo/flutter_inappwebview#1345]
G:\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_inappwebview-5.4.3+8\android\src\main\java\com\pichillilorenzo\flutter_inappwebview\in_app_webview\InAppWebView.java:280: error: cannot find symbol
      settings.setAppCachePath(options.appCachePath);
              ^
  symbol:   method setAppCachePath(String)
  location: variable settings of type WebSettings
G:\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_inappwebview-5.4.3+8\android\src\main\java\com\pichillilorenzo\flutter_inappwebview\in_app_webview\InAppWebView.java:494: error: cannot find symbol
      settings.setAppCacheEnabled(false);
              ^
  symbol:   method setAppCacheEnabled(boolean)
  location: variable settings of type WebSettings
G:\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_inappwebview-5.4.3+8\android\src\main\java\com\pichillilorenzo\flutter_inappwebview\in_app_webview\InAppWebView.java:504: error: cannot find symbol
      settings.setAppCacheEnabled(true);
              ^
  symbol:   method setAppCacheEnabled(boolean)
  location: variable settings of type WebSettings
G:\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_inappwebview-5.4.3+8\android\src\main\java\com\pichillilorenzo\flutter_inappwebview\in_app_webview\InAppWebView.java:515: error: cannot find symbol
        settings.setAppCachePath(ctx.getCacheDir().getAbsolutePath());
                ^
  symbol:   method setAppCachePath(String)
  location: variable settings of type WebSettings
G:\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_inappwebview-5.4.3+8\android\src\main\java\com\pichillilorenzo\flutter_inappwebview\in_app_webview\InAppWebView.java:517: error: cannot find symbol
        settings.setAppCacheEnabled(true);
                ^
  symbol:   method setAppCacheEnabled(boolean)
  location: variable settings of type WebSettings
G:\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_inappwebview-5.4.3+8\android\src\main\java\com\pichillilorenzo\flutter_inappwebview\in_app_webview\InAppWebView.java:521: error: cannot find symbol
      settings.setAppCacheEnabled(false);
              ^
  symbol:   method setAppCacheEnabled(boolean)
  location: variable settings of type WebSettings
G:\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_inappwebview-5.4.3+8\android\src\main\java\com\pichillilorenzo\flutter_inappwebview\in_app_webview\InAppWebView.java:767: error: cannot find symbol
      settings.setAppCachePath(newOptions.appCachePath);
              ^
  symbol:   method setAppCachePath(String)
  location: variable settings of type WebSettings
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
7 errors

**Comment by rennylangat** [comment]
I also experienced the same issue after upgrading dependency to 5.4.3+8

**Comment by pichillilorenzo** [comment]
Released version `5.4.4`
