### ISSUE TITLE
Java:504: error: cannot find symbol

### ISSUE THREAD

**Issue by dpoxo** [pichillilorenzo/flutter_inappwebview#1234]
I keep getting this error whenever i am trying to compile for android

```
\Documents\Flutter\.pub-cache\hosted\pub.dartlang.org\flutter_inappwebview-5.4.3+7\android\src\main\java\com\pichillilorenzo\flutter_inappwebview\in_app_webview\InAppWebView.java:504: error: cannot find symbol
      settings.setAppCacheEnabled(true);

              ^
```
And this results to my build failing...

**Comment by kimonneuhoff** [comment]
Same issue. Did you find a solution?

**Comment by pandaware-admin** [comment]
> Same issue. Did you find a solution?

No I haven't found any yet. Nor have I tried to build the project for Android recently..

But you can try running flutter pub cache repair or flutter clean

**Comment by dpoxo** [comment]
> Same issue. Did you find a solution?

> Same issue. Did you find a solution?

No I haven't found any yet. Nor have I tried to build the project for Android recently..

But you can try running `flutter pub cache repair` or `flutter clean `

**Comment by zegnus** [comment]
I have the same issue

**Comment by sunilguptasg** [comment]
/Applications/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_inappwebview-5.4.3+7/android/src/main/java/com/pichillilorenzo/flutter_inappwebview/in_app_webview/InAppWebView.java:280: error: cannot find symbol
      settings.setAppCachePath(options.appCachePath);
              ^
  symbol:   method setAppCachePath(String)
  location: variable settings of type WebSettings
/Applications/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_inappwebview-5.4.3+7/android/src/main/java/com/pichillilorenzo/flutter_inappwebview/in_app_webview/InAppWebView.java:494: error: cannot find symbol
      settings.setAppCacheEnabled(false);
              ^
  symbol:   method setAppCacheEnabled(boolean)
  location: variable settings of type WebSettings
/Applications/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_inappwebview-5.4.3+7/android/src/main/java/com/pichillilorenzo/flutter_inappwebview/in_app_webview/InAppWebView.java:504: error: cannot find symbol
      settings.setAppCacheEnabled(true);
              ^
  symbol:   method setAppCacheEnabled(boolean)
  location: variable settings of type WebSettings
/Applications/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_inappwebview-5.4.3+7/android/src/main/java/com/pichillilorenzo/flutter_inappwebview/in_app_webview/InAppWebView.java:515: error: cannot find symbol
        settings.setAppCachePath(ctx.getCacheDir().getAbsolutePath());
                ^
  symbol:   method setAppCachePath(String)
  location: variable settings of type WebSettings
/Applications/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_inappwebview-5.4.3+7/android/src/main/java/com/pichillilorenzo/flutter_inappwebview/in_app_webview/InAppWebView.java:517: error: cannot find symbol
        settings.setAppCacheEnabled(true);
                ^
  symbol:   method setAppCacheEnabled(boolean)
  location: variable settings of type WebSettings
/Applications/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_inappwebview-5.4.3+7/android/src/main/java/com/pichillilorenzo/flutter_inappwebview/in_app_webview/InAppWebView.java:521: error: cannot find symbol
      settings.setAppCacheEnabled(false);
              ^
  symbol:   method setAppCacheEnabled(boolean)
  location: variable settings of type WebSettings
/Applications/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_inappwebview-5.4.3+7/android/src/main/java/com/pichillilorenzo/flutter_inappwebview/in_app_webview/InAppWebView.java:767: error: cannot find symbol
      settings.setAppCachePath(newOptions.appCachePath);
              ^
  symbol:   method setAppCachePath(String)
  location: variable settings of type WebSettings
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
7 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flutter_inappwebview:compileDebugJavaWithJavac'.

**Comment by moein-keyvani-pur** [comment]
@sunilguptasg 
Were you able to solve this problem?

**Comment by sunilguptasg** [comment]
Not sure what I did, I downgraded some versions - for me 5.3.2 works.

**Comment by yasaman93** [comment]
@dpoxo
I downgraded to the minimum version with Null safety, but the issue remains. Please help :(
```
flutter_inappwebview\in_app_webview\InAppWebView.java:271: error: cannot find symbol
      settings.setAppCachePath(options.appCachePath);
              ^
  symbol:   method setAppCachePath(String)
  location: variable settings of type WebSettings
```

For me, this issue happens after upgrading Android compileSdkVersion from 32 to 33.

**Comment by vijayvaghela72** [comment]
i am getting same error even i don't use this package any more 
please help how can i solve this issue ?
